# Generated by Django 4.2.9 on 2024-01-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socioghibliuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='socioghibliuser',
            table='accounts_socioghibliuser',
        ),
    ]
