# Generated by Django 4.2.9 on 2024-01-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_socioghibliuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socioghibliuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='socioghibliuser',
            table=None,
        ),
    ]
